const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE:'CHANGE_LANGUAGE', //ACTION CHANGE LANGUAGE 

    //admin
    // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL:"USER_LOGIN_FAIL",
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //ADMIN
    FETCH_GENDER_START:"FETCH_GENDER_START",
    FETCH_GENDER_SUCCESS:"FETCH_GENDER_SUCCESS",
    FETCH_GENDER_FAIL:"FETCH_GENDER_FAIL",

    FETCH_POSITION_START:"FETCH_POSITION_START",
    FETCH_POSITION_SUCCESS:"FETCH_POSITION_SUCCESS",
    FETCH_POSITION_FAIL:"FETCH_POSITION_FAIL",

    FETCH_ROLE_START:"FETCH_ROLE_START",
    FETCH_ROLE_SUCCESS:"FETCH_ROLE_SUCCESS",
    FETCH_ROLE_FAIL:"FETCH_ROLE_FAIL",
    //CREATE USER
    CREATE_USER_SUCCESS:"CREATE_USER_SUCCESS",
    CREATE_USER_FAIL:"CREATE_USER_FAIL",
    //READ USER
    FETCH_ALL_USER_SUCCESS:"FETCH_ALL_USER_SUCCESS",
    FETCH_ALL_USER_FAIL:"FETCH_ALL_USER_FAIL",
    //DELETE USER
    DELETE_USER_SUCCESS:"DELETE_USER_SUCCESS",
    DELETE_USER_FAIL:"DELETE_USER_FAIL",
    //UPDATE USER
    EDIT_USER_SUCCESS:"EDIT_USER_SUCCESS",
    EDIT_USER_FAIL:"EDIT_USER_FAIL",
    //GET USER-DOCTOR
    FETCH_USER_DOCTOR_SUCCESS:"FETCH_USER_DOCTOR_SUCCESS",
    FETCH_USER_DOCTOR_FAIL:"FETCH_USER_DOCTOR_FAIL",
    //GET ALL DOCTORS
    FETCH_ALL_DOCTORS_SUCCESS:"FETCH_ALL_DOCTORS_SUCCESS",
    FETCH_ALL_DOCTORS_FAIL:"FETCH_ALL_DOCTORS_FAIL",
    //CREATE INFO DOCTORS
    CREATE_INFO_DOCTORS_SUCCESS:"CREATE_INFO_DOCTORS_SUCCESS",
    CREATE_INFO_DOCTORS_FAIL:"CREATE_INFO_DOCTORS_FAIL",
    //GET ALL CODE TIME
    FETCH_ALL_CODE_TIME_SUCCESS:"FETCH_ALL_CODE_TIME_SUCCESS",
    FETCH_ALL_CODE_TIME_FAIL:"FETCH_ALL_CODE_TIME_FAIL",
    //GET ALL INFO DOCTOR 
    FETCH_ALL_INFO_DOCTOR_SUCCESS:"FETCH_ALL_INFO_DOCTOR_SUCCESS",
    FETCH_ALL_INFO_DOCTOR_FAIL:"FETCH_ALL_INFO_DOCTOR_FAIL"
})

export default actionTypes;